name: meetingzilla
description: A video calling Flutter application for Android and iOS.

publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  agora_rtc_engine: ^3.2.1
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+3
  uuid: ^2.2.2

  dio: ^3.0.10
  wakelock: ^0.2.1+1
  fluttertoast: ^7.1.6
  get_time_ago: ^0.1.6

  device_info: ^1.0.0
  package_info: ^0.4.3+2
  version: ^1.2.0
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  avatar_glow: ^1.2.0
  font_awesome_flutter: ^8.11.0

  image_picker: ^0.6.7+17
  image_cropper: ^1.3.1
  cached_network_image: ^2.5.0

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_analytics: ^6.3.0
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/